### ISSUE TITLE
Single "end" should be keyword

### ISSUE THREAD

**Issue by jwortmann** [eirik-kjonstad/modern-fortran-syntax#33]
A single `end` is currently highlighted as `variable.language.io.fortran`, which is a bit annoying because it changes its color in many color schemes while typing.

I think it might be better from a highlighting perspective to include a rule like
```yaml
- match: \bend\b
  scope: keyword.control.end.fortran
```
somewhere appropriate to always highlight `end` as keyword. Or maybe use e.g. the scope `keyword.declaration.end.fortran` instead.

**Comment by eirik-kjonstad** [comment]
Yes, this can be annoying. I also noticed it while coding yesterday. I can make a PR with this later tonight (probably).

**Comment by eirik-kjonstad** [comment]
Resolved with release 1.2
