### ISSUE TITLE
Typing "use..." gives incorrect coloring on lines that follow

### ISSUE THREAD

**Issue by eirik-kjonstad** [eirik-kjonstad/modern-fortran-syntax#48]
```fortran
use myModule
!
implicit none
```
looks ok, but
```fortran
use
!
implicit none 
```
does not recognize `!` nor `implicit none` correctly.

**Comment by jwortmann** [comment]
I think you just need to include `eol-pop` in the `find-use-module` context to fix this.

**Comment by eirik-kjonstad** [comment]
Resolved and will be included in 1.3.0
