### ISSUE TITLE
Duplicate entries in the symbol list

### ISSUE THREAD

**Issue by jwortmann** [eirik-kjonstad/modern-fortran-syntax#5]
If a function or subroutine name is repeated after the `end function/subroutine` statement, it will create a duplicate entry in the symbol list for this function/subroutine name. This happens because the identifier uses the scope `entity.name.function` in both cases, which will automatically added to the symbol list by default. But it only makes sense to have a single entry (pointing to the definition line) for the "Goto Symbol" functionality.

Example:
```fortran
function foo(x,y,z)
  ...
end function foo
```

If the same highlighting color for both occurences of the identifier should be kept, one of it could be adjusted to use for example an additional meta scope, and the one after `end` could be excluded from the symbol list via a `.tmPreferences` file then.

I think I could prepare a PR to fix this (I guess I would add proper meta scopes to the function/subroutine definition line in that case).

**Comment by eirik-kjonstad** [comment]
@jwortmann Resolved with PR #8 into development. Will keep issue open until these changes are in main.

I've also added `entity.name.class` to the symbol list in pull request #16. This gives convenient access to class definitions via ctrl+shift+R. We could also consider adding some other entities to the symbol list (program, interface, module, submodule?). Not sure what the user would expect here, but it seems useful if we can easily search for modules via ctrl+shift+R.

**Comment by jwortmann** [comment]
To have `entity.name.class` in the symbol list is definitely useful and your other suggestions look like a good idea to me too 👍

**Comment by eirik-kjonstad** [comment]
Type, program, module, and submodule have now been added to the symbol list in development. Left out interface because it would give duplicates with types in the case of user-defined constructors (`type :: myType` and `interface myType`).

**Comment by eirik-kjonstad** [comment]
Resolved as of `v1.1.0`.
